// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _CotasApi.Data;

#nullable disable

namespace _CotasApi.Migrations
{
    [DbContext(typeof(_CotasContext))]
    [Migration("20260422013452_AddReunionColumns")]
    partial class AddReunionColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("_CotasApi.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarterUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("StarterUserId");

                    b.HasIndex("PetPostId", "StarterUserId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("_CotasApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPost", b =>
                {
                    b.Property<int>("PetPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetKindLabel")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreferredContact")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReunionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReunionDetails")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetPostId");

                    b.HasIndex("UserId");

                    b.ToTable("PetPosts");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPostComment", b =>
                {
                    b.Property<int>("PetPostCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetPostCommentId");

                    b.HasIndex("PetPostId");

                    b.ToTable("PetPostComments");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPostLike", b =>
                {
                    b.Property<int>("PetPostLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PetPostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetPostLikeId");

                    b.HasIndex("PetPostId", "ClientId")
                        .IsUnique();

                    b.ToTable("PetPostLikes");
                });

            modelBuilder.Entity("_CotasApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_CotasApi.Models.Conversation", b =>
                {
                    b.HasOne("_CotasApi.Models.PetPost", "PetPost")
                        .WithMany("Conversations")
                        .HasForeignKey("PetPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_CotasApi.Models.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_CotasApi.Models.User", "StarterUser")
                        .WithMany()
                        .HasForeignKey("StarterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetPost");

                    b.Navigation("ReceiverUser");

                    b.Navigation("StarterUser");
                });

            modelBuilder.Entity("_CotasApi.Models.Message", b =>
                {
                    b.HasOne("_CotasApi.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_CotasApi.Models.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPost", b =>
                {
                    b.HasOne("_CotasApi.Models.User", "User")
                        .WithMany("PetPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPostComment", b =>
                {
                    b.HasOne("_CotasApi.Models.PetPost", "PetPost")
                        .WithMany("Comments")
                        .HasForeignKey("PetPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetPost");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPostLike", b =>
                {
                    b.HasOne("_CotasApi.Models.PetPost", "PetPost")
                        .WithMany("Likes")
                        .HasForeignKey("PetPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetPost");
                });

            modelBuilder.Entity("_CotasApi.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("_CotasApi.Models.PetPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Conversations");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("_CotasApi.Models.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("PetPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
